apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  
helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    releaseName: external-dns
    version: 1.20.0
    namespace: ed
    includeCRDs: true
    additionalValuesFiles:
      - values-prod.yaml