apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-secrets

namespace: es

resources:
  - namespace.yaml
  - css.yaml
  - ces.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    releaseName: external-secrets
    version: 1.2.0
    namespace: es
    includeCRDs: true
    additionalValuesFiles:
      - values-01.yaml
