apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: github-runners

resources:
  - namespace.yaml
  - es.yaml
  - mounted-secrets.yaml

helmCharts:
  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.9.3
    releaseName: oke-runners
    namespace: github-runners
    includeCRDs: false
    valuesFile: values.yaml