apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wikijs
  namespace: wikijs
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik-prod.plagueworks.org
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/cloudflare-comment: "Wiki.js documentation service managed by ExternalDns in oke-prod-zeus-apps"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`wiki.plagueworks.org`)
      kind: Rule
      services:
        - name: wikijs
          port: 80
  tls:
    certResolver: letsencrypt
---
# HTTP to HTTPS redirect
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wikijs-http-redirect
  namespace: wikijs
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik-prod.plagueworks.org
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`wiki.plagueworks.org`)
      kind: Rule
      middlewares:
        - name: https-redirect
          namespace: traefik
      services:
        - name: wikijs
          port: 80