apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wikijs

resources:
  - namespace.yaml
  - es.yaml
  - ingress.yaml

helmCharts:
  - name: wiki
    repo: https://charts.js.wiki
    version: 2.2.22
    releaseName: wikijs
    namespace: wikijs
    additionalValuesFiles: 
      - values-01.yaml