apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: mesapi
  name: mes-api-ingressroute
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik-prod.plagueworks.org
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/cloudflare-comment: "MES API managed by ExternalDns in oke-prod-zeus-apps"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      # IMPORTANT: Replace with the domain you want to use for your API
      match: Host(`staging-mes.plagueworks.org`)
      services:
        - name: mes-api-service # This must match the name of your Service
          port: 80 # This must match the port exposed by your Service
  tls:
    # This assumes you have a cert-resolver named 'le' for Let's Encrypt
    certResolver: le