apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml

helmCharts:
  - name: plagueworks-k8-standard-charts
    repo: oci://ghcr.io/mervinhemaraju
    version: "1.1.0"
    releaseName: mes-api
    namespace: mesapi
    additionalValuesFiles:
      - values-01.yaml