apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: traefik

namespace: traefik

resources:
  - namespace.yaml
  - es.yaml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    releaseName: traefik
    version: 38.0.1
    namespace: traefik
    includeCRDs: true
    additionalValuesFiles:
      - values-01.yaml