apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - es.yaml

helmCharts:
  - name: plagueworks-k8-standard-charts
    repo: oci://ghcr.io/mervinhemaraju
    version: "1.0.0"
    releaseName: koneksyon-api
    namespace: koneksyonapi
    additionalValuesFiles:
      - values-01.yaml